import type {
  DigitKeySchema,
  FunctionKeySchema,
  LetterKeySchema,
  LetterSchema,
  NumpadKeySchema,
} from '../schemas/command'

type KeyboardEventFieldSchema = 'key' | 'code'

type NonAcceleratorSchema = LetterSchema | LetterKeySchema | FunctionKeySchema | DigitKeySchema | NumpadKeySchema

export const keyboardEventFieldByKey: Record<NonAcceleratorSchema, KeyboardEventFieldSchema> = {
  A: 'key',
  B: 'key',
  C: 'key',
  D: 'key',
  E: 'key',
  F: 'key',
  G: 'key',
  H: 'key',
  I: 'key',
  J: 'key',
  K: 'key',
  L: 'key',
  M: 'key',
  N: 'key',
  O: 'key',
  P: 'key',
  Q: 'key',
  R: 'key',
  S: 'key',
  T: 'key',
  U: 'key',
  V: 'key',
  W: 'key',
  X: 'key',
  Y: 'key',
  Z: 'key',
  KeyA: 'code',
  KeyB: 'code',
  KeyC: 'code',
  KeyD: 'code',
  KeyE: 'code',
  KeyF: 'code',
  KeyG: 'code',
  KeyH: 'code',
  KeyI: 'code',
  KeyJ: 'code',
  KeyK: 'code',
  KeyL: 'code',
  KeyM: 'code',
  KeyN: 'code',
  KeyO: 'code',
  KeyP: 'code',
  KeyQ: 'code',
  KeyR: 'code',
  KeyS: 'code',
  KeyT: 'code',
  KeyU: 'code',
  KeyV: 'code',
  KeyW: 'code',
  KeyX: 'code',
  KeyY: 'code',
  KeyZ: 'code',
  F1: 'code',
  F2: 'code',
  F3: 'code',
  F4: 'code',
  F5: 'code',
  F6: 'code',
  F7: 'code',
  F8: 'code',
  F9: 'code',
  F10: 'code',
  F11: 'code',
  F12: 'code',
  Digit0: 'code',
  Digit1: 'code',
  Digit2: 'code',
  Digit3: 'code',
  Digit4: 'code',
  Digit5: 'code',
  Digit6: 'code',
  Digit7: 'code',
  Digit8: 'code',
  Digit9: 'code',
  Numpad0: 'code',
  Numpad1: 'code',
  Numpad2: 'code',
  Numpad3: 'code',
  Numpad4: 'code',
  Numpad5: 'code',
  Numpad6: 'code',
  Numpad7: 'code',
  Numpad8: 'code',
  Numpad9: 'code',
}
